# Generated by Django 3.0.7 on 2020-06-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200630_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firm',
            new_name='Branch',
        ),
    ]
