# Generated by Django 3.0.7 on 2020-07-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200630_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobilePhone',
            new_name='Phone',
        ),
    ]
